In [65]:
import pandas as pd
import numpy as np
import arules as ar

# Substituir '?' por NaN e converter Age para numérico
df['Age'] = df['Age'].replace('?', np.nan)
df['Age'] = pd.to_numeric(df['Age'])

# Definir a função de quantis e converter os intervalos para strings
def five_quantile_based_bins(column):
    return pd.qcut(column, q=5).astype(str)

# Criar uma nova coluna com os intervalos de quantis convertidos para string
df['Age_binned'] = five_quantile_based_bins(df['Age'].dropna())

# Gerar as regras de associação com a coluna de intervalos convertidos
rules, supp_dict = ar.create_association_rules(df, max_cols=2, binning_method=five_quantile_based_bins)

# Mostrar as regras geradas
print(rules)

Calculating all relevant supports
100%|██████████| 45/45 [00:00<00:00, 1247.25it/s]

Calculating all feature level rules per variable level rule
100%|██████████| 72/72 [00:00<00:00, 862.58it/s]
Overall # of Rules:  770
                         antecedent                      consequent  \
0           {'Age': '(25.0, 31.8]'}  {'Age_binned': '(25.0, 31.8]'}
1    {'Age_binned': '(25.0, 31.8]'}         {'Age': '(25.0, 31.8]'}
2           {'Age': '(19.0, 25.0]'}  {'Age_binned': '(19.0, 25.0]'}
3    {'Age_binned': '(19.0, 25.0]'}         {'Age': '(19.0, 25.0]'}
4           {'Age': '(41.0, 80.0]'}  {'Age_binned': '(41.0, 80.0]'}
..                              ...                             ...
765                  {'SibSp': '1'}     {'Fare': '(-0.001, 7.854]'}
766   {'Fare': '(39.688, 512.329]'}                 {'Pclass': '2'}
767                 {'Pclass': '2'}   {'Fare': '(39.688, 512.329]'}
768   {'Fare': '(39.688, 512.329]'}                 {'Pclass': '3'}
769                 {'Pclass': '3'}   {'Fare': '(39.688, 512.329]'}

                                       rule print  ant_count  con_count  \
0    Age=(25.0, 31.8] ==> Age_binned=(25.0, 31.8]        127        127
1    Age_binned=(25.0, 31.8] ==> Age=(25.0, 31.8]        127        127
2    Age=(19.0, 25.0] ==> Age_binned=(19.0, 25.0]        137        137
3    Age_binned=(19.0, 25.0] ==> Age=(19.0, 25.0]        137        137
4    Age=(41.0, 80.0] ==> Age_binned=(41.0, 80.0]        142        142
..                                            ...        ...        ...
765              SibSp=1 ==> Fare=(-0.001, 7.854]        209        179
766           Fare=(39.688, 512.329] ==> Pclass=2        176        184
767           Pclass=2 ==> Fare=(39.688, 512.329]        184        176
768           Fare=(39.688, 512.329] ==> Pclass=3        176        491
769           Pclass=3 ==> Fare=(39.688, 512.329]        491        176

     rule_count  ant_supp  con_supp  rule_supp  confidence    lift  \
0           127  0.142536  0.142536   0.142536      1.0000  7.0157
1           127  0.142536  0.142536   0.142536      1.0000  7.0157
2           137  0.153760  0.153760   0.153760      1.0000  6.5036
3           137  0.153760  0.153760   0.153760      1.0000  6.5036
4           142  0.159371  0.159371   0.159371      1.0000  6.2746
..          ...       ...       ...        ...         ...     ...
765          12  0.234568  0.200898   0.013468      0.0574  0.2858
766          10  0.197531  0.206510   0.011223      0.0568  0.2751
767          10  0.206510  0.197531   0.011223      0.0543  0.2751
768          20  0.197531  0.551066   0.022447      0.1136  0.2062
769          20  0.551066  0.197531   0.022447      0.0407  0.2062

     # of all records
0                 891
1                 891
2                 891
3                 891
4                 891
..                ...
765               891
766               891
767               891
768               891
769               891

[770 rows x 12 columns]

In [67]:
survived = rules[rules['consequent'] == {'Survived': '1'}]
survived = survived[survived['confidence']>0.5]
survived

,antecedent,consequent,rule print,ant_count,con_count,rule_count,ant_supp,con_supp,rule_supp,confidence,lift,# of all records
50,{'Sex': 'female'},{'Survived': '1'},Sex=female ==> Survived=1,314,342,233,0.352413,0.383838,0.261504,0.7420,1.9332,891
74,"{'Fare': '(39.688, 512.329]'}",{'Survived': '1'},"Fare=(39.688, 512.329] ==> Survived=1",176,342,113,0.197531,0.383838,0.126824,0.6420,1.6727,891
78,{'Pclass': '1'},{'Survived': '1'},Pclass=1 ==> Survived=1,216,342,136,0.242424,0.383838,0.152637,0.6296,1.6404,891
104,{'Embarked': 'C'},{'Survived': '1'},Embarked=C ==> Survived=1,168,342,93,0.188552,0.383838,0.104377,0.5536,1.4422,891
108,{'Parch': '1'},{'Survived': '1'},Parch=1 ==> Survived=1,118,342,65,0.132435,0.383838,0.072952,0.5508,1.4351,891
116,{'SibSp': '1'},{'Survived': '1'},SibSp=1 ==> Survived=1,209,342,112,0.234568,0.383838,0.125701,0.5359,1.3961,891